// <auto-generated />
using System;
using Aprendizaje.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aprendizaje.Infraestructura.Migrations
{
    [DbContext(typeof(AprendizajeDbContext))]
    [Migration("20260818153945_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aprendizaje.Dominio.Analytics.SnapshotProgreso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HorasTotales")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PorcentajeGlobal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TemasDominados")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("UQ_SnapshotProgreso_Usuario_Fecha");

                    b.ToTable("SnapshotProgreso", "analytics");
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Evidence.ArtefactoTecnico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContenidoOUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoMadurez")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("N'Borrador'");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEliminacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LenguajeTecnologia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoArtefacto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ArtefactoTecnico", "evidence", t =>
                        {
                            t.HasCheckConstraint("CK_ArtefactoTecnico_EstadoMadurez", "[EstadoMadurez] IN ('Borrador','Documentado','ListoPortafolio','Publicado')");

                            t.HasCheckConstraint("CK_ArtefactoTecnico_Tipo", "[TipoArtefacto] IN ('Script','Herramienta','Cheatsheet','Dashboard','Playbook','ReglaDeteccion','ConsultaSiem','Automatizacion','Plantilla','Otro')");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Evidence.CertificacionObtenida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CertificacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoMadurez")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("N'Documentado'");

                    b.Property<string>("EvidenciaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEliminacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaObtencion")
                        .HasColumnType("date");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CertificacionId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_CertificacionObtenida_UsuarioId");

                    b.ToTable("CertificacionObtenida", "evidence", t =>
                        {
                            t.HasCheckConstraint("CK_CertificacionObtenida_EstadoMadurez", "[EstadoMadurez] IN ('Borrador','Documentado','ListoPortafolio','Publicado')");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Evidence.Laboratorio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntornoVms")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EstadoMadurez")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("N'Borrador'");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEliminacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hallazgos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("TiempoInvertidoMinutos")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Laboratorio", "evidence", t =>
                        {
                            t.HasCheckConstraint("CK_Laboratorio_EstadoMadurez", "[EstadoMadurez] IN ('Borrador','Documentado','ListoPortafolio','Publicado')");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Evidence.Nota", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArtefactoTecnicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEliminacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LaboratorioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProyectoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WriteupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArtefactoTecnicoId")
                        .HasDatabaseName("IX_Nota_ArtefactoTecnicoId")
                        .HasFilter("[ArtefactoTecnicoId] IS NOT NULL");

                    b.HasIndex("LaboratorioId")
                        .HasDatabaseName("IX_Nota_LaboratorioId")
                        .HasFilter("[LaboratorioId] IS NOT NULL");

                    b.HasIndex("ProyectoId")
                        .HasDatabaseName("IX_Nota_ProyectoId")
                        .HasFilter("[ProyectoId] IS NOT NULL");

                    b.HasIndex("TemaId")
                        .HasDatabaseName("IX_Nota_TemaId")
                        .HasFilter("[TemaId] IS NOT NULL");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("WriteupId")
                        .HasDatabaseName("IX_Nota_WriteupId")
                        .HasFilter("[WriteupId] IS NOT NULL");

                    b.ToTable("Nota", "evidence", t =>
                        {
                            t.HasCheckConstraint("CK_Nota_Tipo", "[Tipo] IN ('Nota','Hallazgo','Actualizacion','Autoexplicacion')");

                            t.HasCheckConstraint("CK_Nota_UnSoloPadre", "(CASE WHEN [TemaId] IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN [ProyectoId] IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN [LaboratorioId] IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN [WriteupId] IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN [ArtefactoTecnicoId] IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Evidence.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("N'Idea'");

                    b.Property<string>("EstadoMadurez")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("N'Borrador'");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEliminacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RepositorioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Proyecto", "evidence", t =>
                        {
                            t.HasCheckConstraint("CK_Proyecto_Estado", "[Estado] IN ('Idea','Desarrollo','Documentado','Publicado')");

                            t.HasCheckConstraint("CK_Proyecto_EstadoMadurez", "[EstadoMadurez] IN ('Borrador','Documentado','ListoPortafolio','Publicado')");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Evidence.Writeup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoMadurez")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("N'Borrador'");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEliminacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlataformaOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Writeup", "evidence", t =>
                        {
                            t.HasCheckConstraint("CK_Writeup_EstadoMadurez", "[EstadoMadurez] IN ('Borrador','Documentado','ListoPortafolio','Publicado')");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Integration.Conector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CredencialRef")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EstadoConexion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("N'Desconectado'");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UltimaSincronizacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Plataforma")
                        .IsUnique()
                        .HasDatabaseName("UQ_Conector_Usuario_Plataforma");

                    b.ToTable("Conector", "integration", t =>
                        {
                            t.HasCheckConstraint("CK_Conector_Estado", "[EstadoConexion] IN ('Conectado','Desconectado','Error')");

                            t.HasCheckConstraint("CK_Conector_Plataforma", "[Plataforma] IN ('GitHub','TryHackMe','HackTheBox','NotebookLM','Otro')");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Integration.LogSincronizacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Resumen")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ConectorId", "Fecha")
                        .HasDatabaseName("IX_LogSincronizacion_Conector_Fecha");

                    b.ToTable("LogSincronizacion", "integration", t =>
                        {
                            t.HasCheckConstraint("CK_LogSincronizacion_Resultado", "[Resultado] IN ('Exito','Error','Parcial')");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Nucleo.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CertificacionObjetivoActivaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEliminacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IntervaloRepasoDefectoDias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.HasKey("Id");

                    b.HasIndex("CertificacionObjetivoActivaId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuario_Email");

                    b.ToTable("Usuario", "nucleo");
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Resource.Recurso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("N'PorClasificar'");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEliminacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HerramientaIA")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PromptsUtilizados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Recurso", "resource", t =>
                        {
                            t.HasCheckConstraint("CK_Recurso_Estado", "[Estado] IN ('PorClasificar','PorRevisar','EnUso','Consultado','Referencia')");

                            t.HasCheckConstraint("CK_Recurso_Rating", "[Rating] IS NULL OR [Rating] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Recurso_Tipo", "[Tipo] IN ('Documentacion','Libro','Curso','Video','Laboratorio','Writeup','Cheatsheet','Script','RepositorioGitHub','NotebookIA','Otro')");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Roadmap.Certificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TipoCosto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Certificacion_Nombre");

                    b.ToTable("Certificacion", "roadmap", t =>
                        {
                            t.HasCheckConstraint("CK_Certificacion_TipoCosto", "[TipoCosto] IN ('Gratuita','Pago')");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Roadmap.Competencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Competencia_Usuario_Nombre");

                    b.ToTable("Competencia", "roadmap");
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Roadmap.CriterioTema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Cumplido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaCumplido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TipoCriterio");

                    b.HasKey("Id");

                    b.HasIndex("TemaId")
                        .HasDatabaseName("IX_CriterioTema_TemaId");

                    b.HasIndex("TemaId", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("UQ_CriterioTema_TemaTipo");

                    b.ToTable("CriterioTema", "roadmap", t =>
                        {
                            t.HasCheckConstraint("CK_CriterioTema_Tipo", "[TipoCriterio] IN ('Teoria','Practica','Explicacion','Ejercicios','Laboratorio')");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Roadmap.Fase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Fase_UsuarioId");

                    b.HasIndex("UsuarioId", "Orden")
                        .IsUnique()
                        .HasDatabaseName("UQ_Fase_Usuario_Orden");

                    b.ToTable("Fase", "roadmap");
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Roadmap.Tema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEliminacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TemaPadreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoConocimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<string>("_objetivos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Objetivos");

                    b.HasKey("Id");

                    b.HasIndex("FaseId")
                        .HasDatabaseName("IX_Tema_FaseId");

                    b.HasIndex("TemaPadreId")
                        .HasDatabaseName("IX_Tema_TemaPadreId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Tema_UsuarioId");

                    b.ToTable("Tema", "roadmap", t =>
                        {
                            t.HasCheckConstraint("CK_Tema_Confianza", "[Confianza] IS NULL OR [Confianza] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Tema_Dificultad", "[DificultadPercibida] IS NULL OR [DificultadPercibida] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Tema_NoAutoPadre", "[TemaPadreId] IS NULL OR [TemaPadreId] <> [Id]");

                            t.HasCheckConstraint("CK_Tema_TipoConocimiento", "[TipoConocimiento] IN ('Conceptual','Procedimental','Herramienta')");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Study.EntradaBitacora", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEliminacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.HasIndex("UsuarioId", "Fecha")
                        .HasDatabaseName("IX_EntradaBitacora_Usuario_Fecha");

                    b.ToTable("EntradaBitacora", "study");
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Study.Herramienta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Herramienta_Nombre");

                    b.ToTable("Herramienta", "study");
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Study.SesionEstudio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaEliminacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("TemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("VersionFila")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.HasKey("Id");

                    b.HasIndex("TemaId")
                        .HasDatabaseName("IX_SesionEstudio_TemaId");

                    b.HasIndex("UsuarioId", "Fecha")
                        .HasDatabaseName("IX_SesionEstudio_Usuario_Fecha");

                    b.ToTable("SesionEstudio", "study", t =>
                        {
                            t.HasCheckConstraint("CK_SesionEstudio_Duracion", "[DuracionMinutos] > 0");

                            t.HasCheckConstraint("CK_SesionEstudio_Tipo", "[Tipo] IN ('Teoria','Practica','Laboratorio','Repaso')");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.ArtefactoHerramienta", b =>
                {
                    b.Property<Guid>("ArtefactoTecnicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HerramientaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArtefactoTecnicoId", "HerramientaId");

                    b.HasIndex("HerramientaId")
                        .HasDatabaseName("IX_ArtefactoHerramienta_HerramientaId");

                    b.ToTable("ArtefactoHerramienta", "evidence");
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.ArtefactoTema", b =>
                {
                    b.Property<Guid>("ArtefactoTecnicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArtefactoTecnicoId", "TemaId");

                    b.HasIndex("TemaId")
                        .HasDatabaseName("IX_ArtefactoTema_TemaId");

                    b.ToTable("ArtefactoTema", "evidence");
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.CertificacionTema", b =>
                {
                    b.Property<Guid>("CertificacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("CertificacionId", "TemaId");

                    b.HasIndex("TemaId")
                        .HasDatabaseName("IX_CertificacionTema_TemaId");

                    b.ToTable("CertificacionTema", "roadmap");
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.CompetenciaTema", b =>
                {
                    b.Property<Guid>("CompetenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompetenciaId", "TemaId");

                    b.HasIndex("TemaId")
                        .HasDatabaseName("IX_CompetenciaTema_TemaId");

                    b.ToTable("CompetenciaTema", "roadmap");
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.LaboratorioHerramienta", b =>
                {
                    b.Property<Guid>("LaboratorioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HerramientaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LaboratorioId", "HerramientaId");

                    b.HasIndex("HerramientaId")
                        .HasDatabaseName("IX_LaboratorioHerramienta_HerramientaId");

                    b.ToTable("LaboratorioHerramienta", "evidence");
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.LaboratorioTema", b =>
                {
                    b.Property<Guid>("LaboratorioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LaboratorioId", "TemaId");

                    b.HasIndex("TemaId")
                        .HasDatabaseName("IX_LaboratorioTema_TemaId");

                    b.ToTable("LaboratorioTema", "evidence");
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.ProyectoHerramienta", b =>
                {
                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HerramientaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProyectoId", "HerramientaId");

                    b.HasIndex("HerramientaId")
                        .HasDatabaseName("IX_ProyectoHerramienta_HerramientaId");

                    b.ToTable("ProyectoHerramienta", "evidence");
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.ProyectoTema", b =>
                {
                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProyectoId", "TemaId");

                    b.HasIndex("TemaId")
                        .HasDatabaseName("IX_ProyectoTema_TemaId");

                    b.ToTable("ProyectoTema", "evidence");
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.RecursoTema", b =>
                {
                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecursoId", "TemaId");

                    b.HasIndex("TemaId")
                        .HasDatabaseName("IX_RecursoTema_TemaId");

                    b.ToTable("RecursoTema", "resource");
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.SesionHerramienta", b =>
                {
                    b.Property<Guid>("SesionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HerramientaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SesionId", "HerramientaId");

                    b.HasIndex("HerramientaId")
                        .HasDatabaseName("IX_SesionHerramienta_HerramientaId");

                    b.ToTable("SesionHerramienta", "study");
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.TemaDependencia", b =>
                {
                    b.Property<Guid>("TemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemaRequisitoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TemaId", "TemaRequisitoId");

                    b.HasIndex("TemaRequisitoId")
                        .HasDatabaseName("IX_TemaDependencia_TemaRequisitoId");

                    b.ToTable("TemaDependencia", "roadmap", t =>
                        {
                            t.HasCheckConstraint("CK_TemaDependencia_NoAutoDependencia", "[TemaId] <> [TemaRequisitoId]");
                        });
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.WriteupTema", b =>
                {
                    b.Property<Guid>("WriteupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WriteupId", "TemaId");

                    b.HasIndex("TemaId")
                        .HasDatabaseName("IX_WriteupTema_TemaId");

                    b.ToTable("WriteupTema", "evidence");
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Analytics.SnapshotProgreso", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Evidence.ArtefactoTecnico", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Evidence.CertificacionObtenida", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Roadmap.Certificacion", null)
                        .WithMany()
                        .HasForeignKey("CertificacionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Evidence.Laboratorio", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Evidence.Nota", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Evidence.ArtefactoTecnico", null)
                        .WithMany()
                        .HasForeignKey("ArtefactoTecnicoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Aprendizaje.Dominio.Evidence.Laboratorio", null)
                        .WithMany()
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Aprendizaje.Dominio.Evidence.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Evidence.Writeup", null)
                        .WithMany()
                        .HasForeignKey("WriteupId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Evidence.Proyecto", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Evidence.Writeup", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Integration.Conector", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Integration.LogSincronizacion", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Integration.Conector", null)
                        .WithMany("Logs")
                        .HasForeignKey("ConectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Nucleo.Usuario", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Roadmap.Certificacion", null)
                        .WithMany()
                        .HasForeignKey("CertificacionObjetivoActivaId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Resource.Recurso", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Aprendizaje.Dominio.Resource.ValueObjects.RatingRecurso", "Rating", b1 =>
                        {
                            b1.Property<Guid>("RecursoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte>("Valor")
                                .HasColumnType("tinyint")
                                .HasColumnName("Rating");

                            b1.HasKey("RecursoId");

                            b1.ToTable("Recurso", "resource");

                            b1.WithOwner()
                                .HasForeignKey("RecursoId");
                        });

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Roadmap.Competencia", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Roadmap.CriterioTema", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany("Criterios")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Roadmap.Fase", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Roadmap.Tema", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Roadmap.Fase", null)
                        .WithMany()
                        .HasForeignKey("FaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaPadreId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Aprendizaje.Dominio.Roadmap.ValueObjects.NivelPercepcion", "Confianza", b1 =>
                        {
                            b1.Property<Guid>("TemaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte>("Valor")
                                .HasColumnType("tinyint")
                                .HasColumnName("Confianza");

                            b1.HasKey("TemaId");

                            b1.ToTable("Tema", "roadmap");

                            b1.WithOwner()
                                .HasForeignKey("TemaId");
                        });

                    b.OwnsOne("Aprendizaje.Dominio.Roadmap.ValueObjects.NivelPercepcion", "DificultadPercibida", b1 =>
                        {
                            b1.Property<Guid>("TemaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte>("Valor")
                                .HasColumnType("tinyint")
                                .HasColumnName("DificultadPercibida");

                            b1.HasKey("TemaId");

                            b1.ToTable("Tema", "roadmap");

                            b1.WithOwner()
                                .HasForeignKey("TemaId");
                        });

                    b.OwnsOne("Aprendizaje.Dominio.Roadmap.ValueObjects.IntervaloRepaso", "IntervaloRepaso", b1 =>
                        {
                            b1.Property<Guid>("TemaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Dias")
                                .HasColumnType("int")
                                .HasColumnName("IntervaloRepasoDias");

                            b1.HasKey("TemaId");

                            b1.ToTable("Tema", "roadmap");

                            b1.WithOwner()
                                .HasForeignKey("TemaId");
                        });

                    b.Navigation("Confianza");

                    b.Navigation("DificultadPercibida");

                    b.Navigation("IntervaloRepaso");
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Study.EntradaBitacora", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Study.SesionEstudio", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Nucleo.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.ArtefactoHerramienta", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Evidence.ArtefactoTecnico", null)
                        .WithMany()
                        .HasForeignKey("ArtefactoTecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Study.Herramienta", null)
                        .WithMany()
                        .HasForeignKey("HerramientaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.ArtefactoTema", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Evidence.ArtefactoTecnico", null)
                        .WithMany()
                        .HasForeignKey("ArtefactoTecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.CertificacionTema", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Roadmap.Certificacion", null)
                        .WithMany()
                        .HasForeignKey("CertificacionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.CompetenciaTema", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Roadmap.Competencia", null)
                        .WithMany()
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.LaboratorioHerramienta", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Study.Herramienta", null)
                        .WithMany()
                        .HasForeignKey("HerramientaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Evidence.Laboratorio", null)
                        .WithMany()
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.LaboratorioTema", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Evidence.Laboratorio", null)
                        .WithMany()
                        .HasForeignKey("LaboratorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.ProyectoHerramienta", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Study.Herramienta", null)
                        .WithMany()
                        .HasForeignKey("HerramientaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Evidence.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.ProyectoTema", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Evidence.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.RecursoTema", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Resource.Recurso", null)
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.SesionHerramienta", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Study.Herramienta", null)
                        .WithMany()
                        .HasForeignKey("HerramientaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Study.SesionEstudio", null)
                        .WithMany()
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.TemaDependencia", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaRequisitoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Infraestructura.Persistencia.ModelosUnion.WriteupTema", b =>
                {
                    b.HasOne("Aprendizaje.Dominio.Roadmap.Tema", null)
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Aprendizaje.Dominio.Evidence.Writeup", null)
                        .WithMany()
                        .HasForeignKey("WriteupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Integration.Conector", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Aprendizaje.Dominio.Roadmap.Tema", b =>
                {
                    b.Navigation("Criterios");
                });
#pragma warning restore 612, 618
        }
    }
}
