<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Aprendizaje.Aplicacion</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aprendizaje.Dominio\Aprendizaje.Dominio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Comun\" />
  </ItemGroup>

</Project>
