using Aprendizaje.Api.Endpoints.Evidence;
using Aprendizaje.Api.Endpoints.Nucleo;
using Aprendizaje.Api.Endpoints.Resource;
using Aprendizaje.Api.Endpoints.Roadmap;
using Aprendizaje.Api.Endpoints.Study;
using Aprendizaje.Api.Endpoints;
using Aprendizaje.Aplicacion.Analytics.Certificaciones;
using Aprendizaje.Aplicacion.Analytics.Competencias;
using Aprendizaje.Aplicacion.Analytics.Estudio;
using Aprendizaje.Aplicacion.Analytics.Temas;
using Aprendizaje.Aplicacion.Evidence.ArtefactosTecnicos.ActualizarArtefactoTecnico;
using Aprendizaje.Aplicacion.Evidence.ArtefactosTecnicos.CrearArtefactoTecnico;
using Aprendizaje.Aplicacion.Evidence.ArtefactosTecnicos.EliminarArtefactoTecnico;
using Aprendizaje.Aplicacion.Evidence.ArtefactosTecnicos.ListarArtefactosTecnicos;
using Aprendizaje.Aplicacion.Evidence.ArtefactosTecnicos.ObtenerArtefactoTecnicoPorId;
using Aprendizaje.Aplicacion.Evidence.ArtefactosTecnicos.VincularArtefactoAHerramienta;
using Aprendizaje.Aplicacion.Evidence.ArtefactosTecnicos.VincularArtefactoATema;
using Aprendizaje.Aplicacion.Evidence.CertificacionesObtenidas.ActualizarCertificacionObtenida;
using Aprendizaje.Aplicacion.Evidence.CertificacionesObtenidas.CrearCertificacionObtenida;
using Aprendizaje.Aplicacion.Evidence.CertificacionesObtenidas.EliminarCertificacionObtenida;
using Aprendizaje.Aplicacion.Evidence.CertificacionesObtenidas.ListarCertificacionesObtenidas;
using Aprendizaje.Aplicacion.Evidence.CertificacionesObtenidas.ObtenerCertificacionObtenidaPorId;
using Aprendizaje.Aplicacion.Evidence.Laboratorios.ActualizarLaboratorio;
using Aprendizaje.Aplicacion.Evidence.Laboratorios.CrearLaboratorio;
using Aprendizaje.Aplicacion.Evidence.Laboratorios.EliminarLaboratorio;
using Aprendizaje.Aplicacion.Evidence.Laboratorios.ListarLaboratorios;
using Aprendizaje.Aplicacion.Evidence.Laboratorios.ObtenerLaboratorioPorId;
using Aprendizaje.Aplicacion.Evidence.Laboratorios.VincularLaboratorioAHerramienta;
using Aprendizaje.Aplicacion.Evidence.Laboratorios.VincularLaboratorioATema;
using Aprendizaje.Aplicacion.Evidence.Notas.CrearNotaParaArtefactoTecnico;
using Aprendizaje.Aplicacion.Evidence.Notas.CrearNotaParaLaboratorio;
using Aprendizaje.Aplicacion.Evidence.Notas.CrearNotaParaProyecto;
using Aprendizaje.Aplicacion.Evidence.Notas.CrearNotaParaTema;
using Aprendizaje.Aplicacion.Evidence.Notas.CrearNotaParaWriteup;
using Aprendizaje.Aplicacion.Evidence.Notas.ListarNotas;
using Aprendizaje.Aplicacion.Evidence.Notas.ObtenerNotaPorId;
using Aprendizaje.Aplicacion.Evidence.Proyectos.ActualizarProyecto;
using Aprendizaje.Aplicacion.Evidence.Proyectos.CrearProyecto;
using Aprendizaje.Aplicacion.Evidence.Proyectos.EliminarProyecto;
using Aprendizaje.Aplicacion.Evidence.Proyectos.ListarProyectos;
using Aprendizaje.Aplicacion.Evidence.Proyectos.ObtenerProyectoPorId;
using Aprendizaje.Aplicacion.Evidence.Proyectos.VincularProyectoAHerramienta;
using Aprendizaje.Aplicacion.Evidence.Proyectos.VincularProyectoATema;
using Aprendizaje.Aplicacion.Evidence.Writeups.ActualizarWriteup;
using Aprendizaje.Aplicacion.Evidence.Writeups.CrearWriteup;
using Aprendizaje.Aplicacion.Evidence.Writeups.EliminarWriteup;
using Aprendizaje.Aplicacion.Evidence.Writeups.ListarWriteups;
using Aprendizaje.Aplicacion.Evidence.Writeups.ObtenerWriteupPorId;
using Aprendizaje.Aplicacion.Evidence.Writeups.VincularWriteupATema;
using Aprendizaje.Aplicacion.Nucleo.Usuarios.CrearUsuario;
using Aprendizaje.Aplicacion.Nucleo.Usuarios;
using Aprendizaje.Aplicacion.Portafolio;
using Aprendizaje.Aplicacion.Resource.Recursos.ActualizarRecurso;
using Aprendizaje.Aplicacion.Resource.Recursos.CrearRecurso;
using Aprendizaje.Aplicacion.Resource.Recursos.EliminarRecurso;
using Aprendizaje.Aplicacion.Resource.Recursos.ListarRecursos;
using Aprendizaje.Aplicacion.Resource.Recursos.ObtenerRecursoPorId;
using Aprendizaje.Aplicacion.Resource.Recursos.VincularRecursoATema;
using Aprendizaje.Aplicacion.Roadmap.Fases.ActualizarMetadataPedagogica;
using Aprendizaje.Aplicacion.Roadmap.Fases.CrearFase;
using Aprendizaje.Aplicacion.Roadmap.Fases.ListarFases;
using Aprendizaje.Aplicacion.Roadmap.Certificaciones.CrearCertificacion;
using Aprendizaje.Aplicacion.Roadmap.Certificaciones.ListarCertificaciones;
using Aprendizaje.Aplicacion.Roadmap.Certificaciones.ObtenerCertificacionPorId;
using Aprendizaje.Aplicacion.Roadmap.Certificaciones.VincularCertificacionATema;
using Aprendizaje.Aplicacion.Roadmap.Competencias.CrearCompetencia;
using Aprendizaje.Aplicacion.Roadmap.Competencias.ListarCompetencias;
using Aprendizaje.Aplicacion.Roadmap.Competencias.ObtenerCompetenciaPorId;
using Aprendizaje.Aplicacion.Roadmap.Competencias.VincularCompetenciaATema;
using Aprendizaje.Aplicacion.Roadmap.Temas.ActualizarPercepcion;
using Aprendizaje.Aplicacion.Roadmap.Temas.ActualizarPlanificacion;
using Aprendizaje.Aplicacion.Roadmap.Temas.AsignarTemaAFase;
using Aprendizaje.Aplicacion.Roadmap.Temas.AsignarTemaPadre;
using Aprendizaje.Aplicacion.Roadmap.Temas.ConfigurarIntervaloRepaso;
using Aprendizaje.Aplicacion.Roadmap.Temas.CrearTema;
using Aprendizaje.Aplicacion.Roadmap.Temas.DefinirCriteriosRelevantes;
using Aprendizaje.Aplicacion.Roadmap.Temas.DesmarcarCriterio;
using Aprendizaje.Aplicacion.Roadmap.Temas.EstablecerObjetivos;
using Aprendizaje.Aplicacion.Roadmap.Temas.ListarTemas;
using Aprendizaje.Aplicacion.Roadmap.Temas.MarcarCriterio;
using Aprendizaje.Aplicacion.Roadmap.Temas.ObtenerTemaPorId;
using Aprendizaje.Aplicacion.Roadmap.Temas.ObtenerApuntesTema;
using Aprendizaje.Aplicacion.Roadmap.Temas.GuardarApuntesTema;
using Aprendizaje.Aplicacion.Roadmap.Vistas.RoadmapVistaV1;
using Aprendizaje.Aplicacion.Roadmap.Vistas.TemaWorkspaceV1;
using Aprendizaje.Aplicacion.Study.SesionesEstudio.CorregirDuracionSesionEstudio;
using Aprendizaje.Aplicacion.Study.SesionesEstudio.ActualizarSesionEstudio;
using Aprendizaje.Aplicacion.Study.SesionesEstudio.EliminarSesionEstudio;
using Aprendizaje.Aplicacion.Study.EntradasBitacora.CrearEntradaBitacora;
using Aprendizaje.Aplicacion.Study.EntradasBitacora.ListarEntradasBitacora;
using Aprendizaje.Aplicacion.Study.EntradasBitacora.ObtenerEntradaBitacoraPorId;
using Aprendizaje.Aplicacion.Study.Herramientas.CrearHerramienta;
using Aprendizaje.Aplicacion.Study.Herramientas.ListarHerramientas;
using Aprendizaje.Aplicacion.Study.Herramientas.ObtenerHerramientaPorId;
using Aprendizaje.Aplicacion.Study.SesionesEstudio.ListarSesionesEstudio;
using Aprendizaje.Aplicacion.Study.SesionesEstudio.ObtenerSesionEstudioPorId;
using Aprendizaje.Aplicacion.Study.SesionesEstudio.RegistrarSesionEstudio;
using Aprendizaje.Aplicacion.Study.SesionesEstudio.VincularHerramientaASesionEstudio;
using Aprendizaje.Infraestructura.Configuracion;
using System.Text.Json.Serialization;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddScoped<ObtenerResumenEstudioCasoUso>();
builder.Services.AddScoped<ObtenerResumenTemaCasoUso>();
builder.Services.AddScoped<ObtenerResumenCompetenciasCasoUso>();
builder.Services.AddScoped<ObtenerResumenCertificacionesCasoUso>();
builder.Services.AddScoped<ObtenerPortafolioCasoUso>();
builder.Services.AddScoped<ActualizarMetadataPedagogicaFaseCasoUso>();
builder.Services.AddScoped<CrearFaseCasoUso>();
builder.Services.AddScoped<ListarFasesCasoUso>();
builder.Services.AddScoped<ActualizarPercepcionTemaCasoUso>();
builder.Services.AddScoped<ActualizarPlanificacionTemaCasoUso>();
builder.Services.AddScoped<AsignarTemaAFaseCasoUso>();
builder.Services.AddScoped<AsignarTemaPadreCasoUso>();
builder.Services.AddScoped<ConfigurarIntervaloRepasoTemaCasoUso>();
builder.Services.AddScoped<CrearTemaCasoUso>();
builder.Services.AddScoped<DefinirCriteriosRelevantesTemaCasoUso>();
builder.Services.AddScoped<DesmarcarCriterioTemaCasoUso>();
builder.Services.AddScoped<ObtenerTemaPorIdCasoUso>();
builder.Services.AddScoped<ObtenerApuntesTemaCasoUso>();
builder.Services.AddScoped<GuardarApuntesTemaCasoUso>();
builder.Services.AddScoped<ObtenerRoadmapVistaV1CasoUso>();
builder.Services.AddScoped<ObtenerTemaWorkspaceV1CasoUso>();
builder.Services.AddScoped<EstablecerObjetivosTemaCasoUso>();
builder.Services.AddScoped<ListarTemasCasoUso>();
builder.Services.AddScoped<MarcarCriterioTemaCasoUso>();
builder.Services.AddScoped<CrearUsuarioCasoUso>();
builder.Services.AddScoped<IUsuarioActual, UsuarioActualLocal>();
builder.Services.AddScoped<ActualizarArtefactoTecnicoCasoUso>();
builder.Services.AddScoped<CrearArtefactoTecnicoCasoUso>();
builder.Services.AddScoped<EliminarArtefactoTecnicoCasoUso>();
builder.Services.AddScoped<ListarArtefactosTecnicosCasoUso>();
builder.Services.AddScoped<ObtenerArtefactoTecnicoPorIdCasoUso>();
builder.Services.AddScoped<VincularArtefactoAHerramientaCasoUso>();
builder.Services.AddScoped<VincularArtefactoATemaCasoUso>();
builder.Services.AddScoped<ActualizarCertificacionObtenidaCasoUso>();
builder.Services.AddScoped<CrearCertificacionObtenidaCasoUso>();
builder.Services.AddScoped<EliminarCertificacionObtenidaCasoUso>();
builder.Services.AddScoped<ListarCertificacionesObtenidasCasoUso>();
builder.Services.AddScoped<ObtenerCertificacionObtenidaPorIdCasoUso>();
builder.Services.AddScoped<ActualizarLaboratorioCasoUso>();
builder.Services.AddScoped<CrearLaboratorioCasoUso>();
builder.Services.AddScoped<EliminarLaboratorioCasoUso>();
builder.Services.AddScoped<ListarLaboratoriosCasoUso>();
builder.Services.AddScoped<ObtenerLaboratorioPorIdCasoUso>();
builder.Services.AddScoped<VincularLaboratorioAHerramientaCasoUso>();
builder.Services.AddScoped<VincularLaboratorioATemaCasoUso>();
builder.Services.AddScoped<CrearNotaParaArtefactoTecnicoCasoUso>();
builder.Services.AddScoped<CrearNotaParaLaboratorioCasoUso>();
builder.Services.AddScoped<CrearNotaParaProyectoCasoUso>();
builder.Services.AddScoped<CrearNotaParaTemaCasoUso>();
builder.Services.AddScoped<CrearNotaParaWriteupCasoUso>();
builder.Services.AddScoped<ListarNotasCasoUso>();
builder.Services.AddScoped<ObtenerNotaPorIdCasoUso>();
builder.Services.AddScoped<ActualizarProyectoCasoUso>();
builder.Services.AddScoped<CrearProyectoCasoUso>();
builder.Services.AddScoped<EliminarProyectoCasoUso>();
builder.Services.AddScoped<ListarProyectosCasoUso>();
builder.Services.AddScoped<ObtenerProyectoPorIdCasoUso>();
builder.Services.AddScoped<VincularProyectoAHerramientaCasoUso>();
builder.Services.AddScoped<VincularProyectoATemaCasoUso>();
builder.Services.AddScoped<ActualizarWriteupCasoUso>();
builder.Services.AddScoped<CrearWriteupCasoUso>();
builder.Services.AddScoped<EliminarWriteupCasoUso>();
builder.Services.AddScoped<ListarWriteupsCasoUso>();
builder.Services.AddScoped<ObtenerWriteupPorIdCasoUso>();
builder.Services.AddScoped<VincularWriteupATemaCasoUso>();
builder.Services.AddScoped<CrearRecursoCasoUso>();
builder.Services.AddScoped<ActualizarRecursoCasoUso>();
builder.Services.AddScoped<EliminarRecursoCasoUso>();
builder.Services.AddScoped<ListarRecursosCasoUso>();
builder.Services.AddScoped<ObtenerRecursoPorIdCasoUso>();
builder.Services.AddScoped<VincularRecursoATemaCasoUso>();
builder.Services.AddScoped<ActualizarSesionEstudioCasoUso>();
builder.Services.AddScoped<CorregirDuracionSesionEstudioCasoUso>();
builder.Services.AddScoped<EliminarSesionEstudioCasoUso>();
builder.Services.AddScoped<CrearCertificacionCasoUso>();
builder.Services.AddScoped<ListarCertificacionesCasoUso>();
builder.Services.AddScoped<ObtenerCertificacionPorIdCasoUso>();
builder.Services.AddScoped<VincularCertificacionATemaCasoUso>();
builder.Services.AddScoped<CrearCompetenciaCasoUso>();
builder.Services.AddScoped<ListarCompetenciasCasoUso>();
builder.Services.AddScoped<ObtenerCompetenciaPorIdCasoUso>();
builder.Services.AddScoped<VincularCompetenciaATemaCasoUso>();
builder.Services.AddScoped<CrearEntradaBitacoraCasoUso>();
builder.Services.AddScoped<ListarEntradasBitacoraCasoUso>();
builder.Services.AddScoped<ObtenerEntradaBitacoraPorIdCasoUso>();
builder.Services.AddScoped<CrearHerramientaCasoUso>();
builder.Services.AddScoped<ListarHerramientasCasoUso>();
builder.Services.AddScoped<ObtenerHerramientaPorIdCasoUso>();
builder.Services.AddScoped<ListarSesionesEstudioCasoUso>();
builder.Services.AddScoped<ObtenerSesionEstudioPorIdCasoUso>();
builder.Services.AddScoped<RegistrarSesionEstudioCasoUso>();
builder.Services.AddScoped<VincularHerramientaASesionEstudioCasoUso>();
builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.Converters.Add(new JsonStringEnumConverter());
});
builder.Services.AddInfraestructura(builder.Configuration);

var app = builder.Build();

app.MapAnalyticsEstudioEndpoints();
app.MapAnalyticsTemaEndpoints();
app.MapAnalyticsCompetenciaEndpoints();
app.MapAnalyticsCertificacionEndpoints();
app.MapArtefactoTecnicoEndpoints();
app.MapCertificacionEndpoints();
app.MapCertificacionObtenidaEndpoints();
app.MapCompetenciaEndpoints();
app.MapEntradaBitacoraEndpoints();
app.MapFaseEndpoints();
app.MapHerramientaEndpoints();
app.MapLaboratorioEndpoints();
app.MapNotaEndpoints();
app.MapPortafolioEndpoints();
app.MapProyectoEndpoints();
app.MapRecursoEndpoints();
app.MapRoadmapVistaEndpoints();
app.MapSesionEstudioEndpoints();
app.MapTemaEndpoints();
app.MapTemaWorkspaceEndpoints();
app.MapUsuarioActualEndpoints();
app.MapUsuarioEndpoints();
app.MapWriteupEndpoints();

app.Run();
