namespace Aprendizaje.Aplicacion.Evidence.CertificacionesObtenidas.ListarCertificacionesObtenidas;

public sealed record ListarCertificacionesObtenidasResultado(
    IReadOnlyCollection<CertificacionObtenidaResumen> CertificacionesObtenidas);
