namespace Aprendizaje.Aplicacion.Evidence.ArtefactosTecnicos.ListarArtefactosTecnicos;

public sealed record ListarArtefactosTecnicosResultado(IReadOnlyCollection<ArtefactoTecnicoResumen> ArtefactosTecnicos);
